"""Regenerate the diagrams in ../*.md from the page sources in this folder.

Run from anywhere: python3 3-driver/blocks/_src/build.py
Each page source (e.g. usb.py) builds a Diagram named D. Its art and connection list
replace the generated block between the BEGIN/END markers in the matching .md.
"""
import importlib, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
PAGES = {
    'overview': '0-overview.md',
    'power': '1-power.md',
    'scsi': '2-scsi-frontend.md',
    'mcu': '3-mcu-support.md',
    'usb': '4-usb.md',
}
BEGIN = '<!-- BEGIN generated by _src/build.py from _src/{src}.py: edit the source, not this block -->'
END = '<!-- END generated -->'

sys.path.insert(0, str(HERE))
failed = False
for src, md in PAGES.items():
    try:
        D = importlib.import_module(src).D
        art = D.render()
    except Exception as e:  # report every broken page, not just the first
        print(f"{src}.py: {type(e).__name__}: {e}")
        failed = True
        continue
    conns = '\n'.join(f'- {c}' for c in D.connections())
    block = (f"{BEGIN.format(src=src)}\n```\n{art}\n```\n\n"
             f"<details><summary>Connections (from the source, for readers who'd rather not trace lines)</summary>\n\n"
             f"{conns}\n\n</details>\n{END}")
    path = HERE.parent / md
    text = path.read_text()
    pat = re.compile(re.escape(BEGIN.format(src=src)) + r'.*?' + re.escape(END), re.S)
    if not pat.search(text):
        raise SystemExit(f"{md}: no BEGIN/END markers for {src}.py")
    path.write_text(pat.sub(lambda _: block, text))
    print(f"{src}.py -> {md} ({len(art.splitlines())} lines, {len(D.links)} links)")
sys.exit(1 if failed else 0)
